### PR TITLE
✨ Introducing BigCairo Inscription Marketplace

### PR DESCRIPTION
**Pull request by Robert8866**
Dear Starket Ecosystem Team,

I am writing to express my intention to create a pull request introducing our Inscription Marketplace on the Starknet mainnet. Should you have any questions or concerns, please do not hesitate to reach out to us.

Your assistance and support are greatly appreciated!

Best regards,

### CODE REVIEW

**Comment by 0xlny** [comment]
Hey @Robert8866 thanks for your contribution! Can you please fix the linter? npm run lint --fix or yarn lint --fix

**Comment by Robert8866** [comment]
Hi  @0xlny 

I've just fixed the linter. Could you please help me to review it again?

Thanks and Best Regards!

**Review by 0xlny — APPROVED** [review]
LGTM

**Comment by Robert8866** [comment]
Hi @0xlny,

That's amazing! Thank you for your effort in supporting us.
I'm wondering if it would be possible for the Starknet ecosystem to introduce us as the new project coming to the ecosystem via a Starknet Ecosystem Twitter handle?

I appreciate your help

**Pull request merged**
