### PR TITLE
🎨 Updating zkLend

### PR DESCRIPTION
**Pull request by stacey-zklend**

### CODE REVIEW

**Comment by 0xlny** [comment]
Hey @stacey-zklend can you please update your PR to keep the same project key as before? Thanks

**Comment by stacey-zklend** [comment]
Hi, updated code and the change on project key is reverted. Thanks @0xlny.

**Comment by 0xlny** [comment]
@stacey-zklend Can you fix the linter as well? You can run `yarn lint --fix (or npm run lint --fix)`

**Comment by stacey-zklend** [comment]
@0xlny updated and fixed, thanks.

**Review by 0xlny — APPROVED** [review]
LGTM

**Pull request merged**
