### PR TITLE
✨ Introducing OmniBTC

### PR DESCRIPTION
**Pull request by JJuuneezcx**
OmniBTC is an omnichain defi platform based on interoperability protocols to realize cross-chain swap/lending across multi-VM ecosystems, aiming to provide users with the best cross-chain experience at the lowest cost.

Now we support StarkNet/zkSync Era/Ethereum/Polygon/Arbitrum/Optimism/BNB Chain/Avalanche/Aptos.

### CODE REVIEW

**Comment by 0xMentorNotAPseudo** [comment]
Are you live on Starknet or do you have any public way to see you're involved in the ecosystem?

**Comment by JJuuneezcx** [comment]
微信图片_20230515101417
Yep, we have supported Starknet now. Now users can realize cross-chain swap from Arbitrum/Optimism/zkSync Era to Starknet.

**Comment by 0xlny** [comment]
Hey @JJuuneezcx can you pls fix the linter & fix conflicts ?

**Comment by JJuuneezcx** [comment]
We have fixed the problem, thank you

**Comment by 0xlny** [comment]
@JJuuneezcx the linter is now ok but can you pls fix conflicts ? By merging main branch to your branch thanks

**Comment by JJuuneezcx** [comment]
How about now? Thanks a lot

**Comment by 0xlny** [comment]
It seems you just updated another project by yours, please add a new project by following this https://github.com/419Labs/starknet-ecosystem.com/blob/main/docs/add-project.md

**Comment by JJuuneezcx** [comment]
nop, just OmniBTC, it seems that there is something wrong business ***@***.*** 签名由 网易邮箱大师 定制 On 05/20/2023 15:13, 0xlenny wrote: It seems you just updated another project by yours, please add a new project by following this https://github.com/419Labs/starknet-ecosystem.com/blob/main/docs/add-project.md — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by 0xlny** [comment]
I opened another PR

**Pull request closed without merging**
