### PR TITLE
chore: adding starknet-rs logo

### PR DESCRIPTION
**Pull request by milancermak**
This, hopefully, adds a logo to the Starknet-rs project.

### CODE REVIEW

**Review by m-reka — APPROVED** [review]

**Comment by m-reka** [comment]
LGTM. Thank your Ser!

**Comment by xJonathanLEI** [comment]
LOL nice job man

**Comment by milancermak** [comment]
This awesome logo deserves to be seen ;)

**Comment by m-reka** [comment]
I agree Ser 🤘

**Pull request merged**
