### PR TITLE
Introducing Resmic

### PR DESCRIPTION
**Pull request by adityakaklij**

### CODE REVIEW

**Comment by 0xlny** [comment]
Hey @adityakaklij thanks for your contribution, can you please point us some links where you explain your involvement on Starknet? Thanks

**Comment by adityakaklij** [comment]
> Hey @adityakaklij thanks for your contribution, can you please point us some links where you explain your involvement on Starknet? Thanks

Please have a look into it https://docs.resmic.com/getting-started/usage/for-starknet

**Comment by 0xlny** [comment]
@adityakaklij Can you please fix the linter? (yarn lint --fix or npm run lint --fix)

**Comment by adityakaklij** [comment]
Done with (yarn lint --fix).

**Review by 0xlny — APPROVED** [review]
LGTM

**Pull request merged**
