### PR TITLE
✨ Introducing CHEDAO & AW Research

### PR DESCRIPTION
**Pull request by FrostStarBook**

### CODE REVIEW

**Comment by 0xlny** [comment]
Hey @FrostStarBook thanks for your contribution, can you please fix the linter? (npm run lint --fix or yarn lint --fix)

**Comment by FrostStarBook** [comment]
> Hey @FrostStarBook thanks for your contribution, can you please fix the linter? (npm run lint --fix or yarn lint --fix)

No problem, I have fixed it

**Comment by FrostStarBook** [comment]
The fix has been completed, can you help merge? @0xlny

**Comment by FrostStarBook** [comment]
> Hey @FrostStarBook I don't have write access to your branch to fix conflicts, can you do it pls? Will merge right after

Hey @0xlny ,I have re-pulled the latest code and resolved the conflicts. I have re-submitted a new PR.

**Pull request closed without merging**
