### PR TITLE
✨ Introducing Stark Inu - Onchain Casino

### PR DESCRIPTION
**Pull request by 100x-dev**

### CODE REVIEW

**Comment by 0xlny** [comment]
Hey @100x-dev thanks for your contribution, can you please fix the linter ? (npm run lint --fix or yarn lint --fix)

**Comment by 100x-dev** [comment]
Done!

**Comment by 0xlny** [comment]
> Done!

Can you resolve conflicts as well? Thanks

**Review by 0xlny — APPROVED** [review]
LGTM

**Pull request merged**
