### PR TITLE
✨ Introducing Astarion

### PR DESCRIPTION
**Pull request by ASTARIONCrypto**

### CODE REVIEW

**Comment by 0xlny** [comment]
Hey @ASTARIONCrypto  thanks for your contribution, can you please fix the linter? (npm run lint --fix or yarn lint --fix)

**Comment by ASTARIONCrypto** [comment]
Hey 0xlny, dont understand, what is wrong, can you help me? how should i understand the error? 34:3  Error: Delete `··`  prettier/prettier

**Comment by ASTARIONCrypto** [comment]
Hi, do you need something from me in oder to merge or should i just wait?

**Review by 0xlny — APPROVED** [review]
LGTM

**Pull request merged**
