### PR TITLE
✨ Introducing RN Bridge from Raum Network

### PR DESCRIPTION
**Pull request by Zypheraum**

### CODE REVIEW

**Comment by 0xlny** [comment]
Hey @Zypheraum thanks for your contribution, can you please fix the linter please? (npm run lint --fix)

**Review by Zypheraum — COMMENTED** [review]
Updated

**Comment by Zypheraum** [comment]
Hi lenny,

I have updated to the code. Kindly approve for the merge.

Thanks

**Review by 0xlny — APPROVED** [review]
LGTM

**Pull request merged**
