### PR TITLE
✨ Introducing Nomis Protocol

### PR DESCRIPTION
**Pull request by unchase**

### CODE REVIEW

**Review by 0xMentorNotAPseudo — APPROVED** [review]
LGTM!

**Comment by 0xlny** [comment]
Hey @unchase thanks for your contribution! Can you please fix the linter? npm run lint --fix or yarn lint --fix

**Comment by unchase** [comment]
> npm run lint --fix

Hi, @0xlny 
Done!

**Comment by unchase** [comment]
@0xMentorNotAPseudo 

Discovered after posting that the banner for Nomis is not showing on the [Nomis page](https://www.starknet-ecosystem.com/projects/9bc521e4-980e-4ae3-99e8-083f10efbdaa).

Could you please advise what needs to be added to the project ()github files to fix this?

image

**Comment by unchase** [comment]
@0xlny @0xMentorNotAPseudo could you help me with this issue?

**Pull request merged**
