### PR TITLE
✨ Introducing rhino.fi

### PR DESCRIPTION
**Pull request by nicob21**

### CODE REVIEW

**Comment by 0xlny** [comment]
Hey @nicob21 thanks for your contribution, can you please fix the linter? (npm run lint --fix or yarn lint --fix)

**Comment by nicob21** [comment]
@0xlny sure, just done it

**Review by 0xlny — APPROVED** [review]
LGTM

**Comment by nicob21** [comment]
Thanks @0xlny
How can we set the background image of our card?

**Pull request merged**
